### ISSUE TITLE
H4/H7 HiSky airline - lack of seatmap

### ISSUE THREAD

**Issue by aleksandrajendrzejczak** [Kwiket/jets-seatmap-react-lib-pub#2]
Hello Team, 

We encounter many issues with lack of seat map for H4/H7 HiSky airline. In the past week we had this issue for approximately 20% of the cases. Could you please check it on your side? 

Here is the example: 

{,…}
flight
: 
{id: "1", airlineCode: "H4", flightNo: "422", departureDate: "2024-02-04", departure: "IST",…}
airlineCode
: 
"H4"
arrival
: 
"RMO"
cabinClass
: 
"E"
departure
: 
"IST"
departureDate
: 
"2024-02-04"
endRow
: 
30
flightNo
: 
"422"
id
: 
"1"
passengerType
: 
"ADT"
planeCode
: 
""
startRow
: 
1
lang
: 
"EN"
units
: 
"metric"

Thank you in advance. 

Best regards,
Aleksandra

**Comment by nexus** [comment]
Dear @aleksandrajendrzejczak 
this issue is related to the lack of a schedule for flight: H4-422. 
For flight H7-422 we have data, please try:
```
{
  "id": "111",
  "airlineCode": "H7",
  "flightNo": "422",
  "departureDate": "2024-02-04",
  "departure": "IST",
  "arrival": "RMO",
  "cabinClass": "E",
  "planeCode": ""
}
```
